name: Node Continuous Integration

on:
  push:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
      - run: yarn install
      - run: yarn run actionTest
